name: Multi-Container Deployment with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode package

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v4

      # Step 2: SSH into Lightsail and deploy
      - name: SSH into Lightsail and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}       # Your Lightsail instance public IP or DNS
          username: ${{ secrets.SSH_USER }}   # Your SSH username (e.g., ubuntu)
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Your SSH private key for authentication hell
          script: |
            echo "Deploying application to Lightsail instance..."
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo apt-get install -y docker-compose
            sudo usermod -aG docker $USER 
            if [ -d "demo-project" ]; then
            echo "Removing the existing 'demo-project' repository..."
            rm -rf demo-project
            fi
            echo "Cloning the repository from GitHub..."
            git clone https://github.com/aime-byiringiro/demo-project.git
            cd demo-project || exit
            pwd
            ls
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d
            docker-compose -f docker-compose.yml ps
            docker-compose -f docker-compose.yml logs
